server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    location /api {
        proxy_pass ${BACKEND_URL};
        proxy_ssl_verify off;
        proxy_hide_header Cache-Control;
        add_header Cache-Control "no-store, no-cache, must-revalidate";
    }

    location /generate-captcha {
        proxy_pass ${BACKEND_URL};
        proxy_ssl_verify off;
        proxy_hide_header Cache-Control;
        add_header Cache-Control "no-store, no-cache, must-revalidate";
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
